name: Version Bump and Tag
on:
  push:
    branches:
      - main  # or your default branch

jobs:
  version-bump:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Important for git history

      - name: Get latest tag
        id: get-latest-tag
        run: |
          # Get the latest tag, if none exists default to 0.0.0
          LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1` 2>/dev/null || echo "0.0.0")
          echo "LATEST_TAG=${LATEST_TAG}" >> $GITHUB_OUTPUT

      - name: Bump version
        id: bump-version
        run: |
          # Parse the latest tag
          IFS='.' read -r MAJOR MINOR PATCH <<< "${LATEST_TAG//[^0-9.]/ }"
          
          # Increment patch version
          NEW_PATCH=$((PATCH + 1))
          NEW_VERSION="${MAJOR}.${MINOR}.${NEW_PATCH}"
          
          echo "NEW_VERSION=${NEW_VERSION}" >> $GITHUB_OUTPUT

      - name: Create and push tag
        run: |
          NEW_VERSION=${{ steps.bump-version.outputs.NEW_VERSION }}
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag -a "v${NEW_VERSION}" -m "Release version ${NEW_VERSION}"
          git push origin "v${NEW_VERSION}" 